### ISSUE TITLE
iOS 14 Update

### ISSUE THREAD

**Issue by thiagograndesso** [RoepStoep/lidraughts#10]
Hi team,

With the iOS 14 update a few screens have icons hidden and minor layout changes are noticed in Safari browser (the only browser I verified). Would this be something you'd like to fix?
![image](https://user-images.githubusercontent.com/12720624/93662035-16d23980-fa5d-11ea-801c-a4fc6985523c.png)

**Comment by niklasf** [comment]
Equivalent lila issue: https://github.com/ornicar/lila/issues/7323. Probably a WebKit bug. We haven't found a workaround, yet.

**Comment by RoepStoep** [comment]
Safari - the new IE, but in 2020
I'll give it a shot to find a workaround, I've seen the weirdest css-magic in Safari before

**Comment by ornicar** [comment]
https://github.com/ornicar/lila/commit/7618f418ff6e199f4995313e3bc3be0b082eee48
