### ISSUE TITLE
More variant support? In particular English/American draughts?

### ISSUE THREAD

**Issue by autovalue** [RoepStoep/lidraughts#12]
Is there a reason certain rule variants like English draughts aren't currently supported?

This was the variant of the game I was most familiar with, and was surprised it wasn't as popular as I thought.

Based on this [wikipedia article](https://en.wikipedia.org/wiki/Draughts#National_and_regional_variants) (there's way more variants with varying capture constraints than I thought!), the main distinction between the currently supported variants and English draught are:
- No Flying kings
- Men cannot capture backwards.

It'd kinda cool be nice if all these rules and constraints were configurable, allowing users to play custom games with mixed rules without forcing developers to release a new variant each time.

**Comment by RoepStoep** [comment]
There are many different draughts variants, and the aim of lidraughts is not to have them all. But we are moving towards supporting those draughts variants with the biggest real world representation (world championship cycles, international tournament, official titles / ratings, etc), which includes the variants you mention.

At this point in time the focus is first on expand features for the existing variants (e.g. Russian and Brazilian engine), and in more general directions (e.g. Swiss Tournaments and an Opening Explorer). But when new variants are added, very likely candidates are those without flying kings: English, American and Italian draughts.

See also https://github.com/RoepStoep/lidraughts/issues/14
