### ISSUE TITLE
Translations: "haveAnAccount" not used anymore? 

### ISSUE THREAD

**Issue by Trinitit** [RoepStoep/lidraughts#17]
I'm currently adding german translations for the site.xml

In de-DE.xml (and quite a few other languages) there exists an attribute called "haveAnAccount" which seems to not be used anymore. 

Is my assumption correct or am I missing something? 
![haveAnAccount_search](https://user-images.githubusercontent.com/76884934/112279086-cba31880-8c83-11eb-8c4e-00eeafcbf75e.png)

**Comment by RoepStoep** [comment]
That is correct, this key is unused since the v2-interface
