### ISSUE TITLE
Multi-capture promotion

### ISSUE THREAD

**Issue by ddugovic** [RoepStoep/lidraughts#2]
Pardon my ignorance of the rules, but should 11... 36x38 be a promotion move?  I can't seem to find an official rules set anywhere online:
https://lidraughts.org/7CrnSz96/white#21

**Comment by RoepStoep** [comment]
You only promote when your turn ends at a promotion square, not when you "pass through" during a capture. You can find the rules here, this is explained at the King section:
https://lidraughts.org/variant/standard

**Comment by RoepStoep** [comment]
By the way, we just created a discord for lidraughts, if you have any other questions you could also go there: https://discord.gg/MjYecr5

**Comment by jmschl96** [comment]
can you put the discord link on the website so everyone sees it ? :)
