### ISSUE TITLE
Onboarding?

### ISSUE THREAD

**Issue by lw1990** [RoepStoep/lidraughts#4]
Can someone explain the steps for setting up a development environment for this project?

**Comment by ddugovic** [comment]
I've started on https://github.com/ddugovic/lichocker/tree/openjdk-draughts but still have work to do...

**Comment by lw1990** [comment]
I noticed that, but that doesn't even explain how to get it working without docker.
It seems as if lichess is designed to be developed with linux, and lidraughts is designed to be developed with windows (out of the box). lidraughts has dev.bat and build.bat, which are windows files.

I have windows 10, and all of the 'prerequisites' from lichess (windows) onboarding like sbt, but I can't seem to get it to work. The first thing it complains about is that application.conf doesn't exist, which it doesn't, on this repo.

**Comment by lw1990** [comment]
I tried following the lichess (windows) onboarding closely except modifying for lidraughts (for example, in the application.conf and nginx server block)

The app compiles and at localhost:9663 I can see the empty dashboard/lobby, but I can't start a match or do anything like register (mongod and nginx are both running, I've set up lichess before)

The problem seems to be ui/build.bat, which throws a bunch of errors pasted below

`C:\git\lidraughts\ui>build.bat
A subdirectory or file public\compiled already exists.
yarn install v1.7.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.72s.
Building TypeScript: common
The system cannot find the path specified.
yarn run v1.7.0
error Command "compile" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building TypeScript: draughts
The system cannot find the path specified.
yarn run v1.7.0
error Couldn't find a package.json file in "C:\\git"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building TypeScript: ceval
The system cannot find the path specified.
yarn run v1.7.0
error Couldn't find a package.json file in "C:\\"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building TypeScript: game
The system cannot find the path specified.
yarn run v1.7.0
error Couldn't find a package.json file in "C:\\"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building TypeScript: tree
The system cannot find the path specified.
yarn run v1.7.0
error Couldn't find a package.json file in "C:\\"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building TypeScript: chat
The system cannot find the path specified.
yarn run v1.7.0
error Couldn't find a package.json file in "C:\\"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building TypeScript: draughtsground
The system cannot find the path specified.
yarn run v1.7.0
error Couldn't find a package.json file in "C:\\"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Building: draughtsground stand alone
The system cannot find the path specified.
[05:37:05] Local gulp not found in C:\
[05:37:05] Try running: npm install gulp
[05:37:05] Local gulp not found in C:\
[05:37:06] Try running: npm install gulp
File not found - draughtsground.min.js
0 File(s) copied
Building: site
The system cannot find the path specified.
[05:37:06] Local gulp not found in C:\
[05:37:06] Try running: npm install gulp
Building: challenge
The system cannot find the path specified.
[05:37:07] Local gulp not found in C:\
[05:37:07] Try running: npm install gulp
Building: notify
The system cannot find the path specified.
[05:37:07] Local gulp not found in C:\
[05:37:07] Try running: npm install gulp
Building: round
The system cannot find the path specified.
[05:37:08] Local gulp not found in C:\
[05:37:08] Try running: npm install gulp
Building: analyse
The system cannot find the path specified.
[05:37:08] Local gulp not found in C:\
[05:37:08] Try running: npm install gulp
Building: editor
The system cannot find the path specified.
[05:37:09] Local gulp not found in C:\
[05:37:09] Try running: npm install gulp
Building: puzzle
The system cannot find the path specified.
[05:37:09] Local gulp not found in C:\
[05:37:10] Try running: npm install gulp
Building: lobby
The system cannot find the path specified.
[05:37:10] Local gulp not found in C:\
[05:37:10] Try running: npm install gulp
Building: tournament
The system cannot find the path specified.
[05:37:11] Local gulp not found in C:\
[05:37:11] Try running: npm install gulp
Building: tournamentSchedule
The system cannot find the path specified.
[05:37:11] Local gulp not found in C:\
[05:37:11] Try running: npm install gulp
Building: tournamentCalendar
The system cannot find the path specified.
[05:37:12] Local gulp not found in C:\
[05:37:12] Try running: npm install gulp
Building: simul
The system cannot find the path specified.
[05:37:12] Local gulp not found in C:\
[05:37:12] Try running: npm install gulp
Building: perfStat
The system cannot find the path specified.
[05:37:13] Local gulp not found in C:\
[05:37:13] Try running: npm install gulp
Building: dasher
The system cannot find the path specified.
[05:37:13] Local gulp not found in C:\
[05:37:13] Try running: npm install gulp
Building: cli
The system cannot find the path specified.
[05:37:14] Local gulp not found in C:\
[05:37:14] Try running: npm install gulp
Building: editor.min
The system cannot find the path specified.
[05:37:15] Local gulp not found in C:\
[05:37:15] Try running: npm install gulp`

**Comment by RoepStoep** [comment]
all the steps of https://github.com/ornicar/lila/wiki/Lichess-Development-Onboarding-(Windows) should work for lidraughts

I think the problem is that you're not running the script from the project root, e.g. try 
C:\git\lidraughts>.\ui\build.bat

**Comment by lw1990** [comment]
Running the script from the project root was the fix, thanks!
Everything seems to be compiling/running fine now except I can't create games on the local environment nor register/sign in. Just nothing happens (even in the console), except when trying to sign in. When trying to sign in I get an error "Cross origin request forbidden" in the browser, and this in the console: 

> [info] csrf - POST localhost/login 0:0:0:0:0:0:0:1 origin:http://localhost:9663 referer:http://localhost:9663/login ua:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

If you don't know why this is, can you share what your devolopment environment is? Is it windows-based?
Is it local or running on a web server?
