### ISSUE TITLE
Tournament description not displayed on mobile

### ISSUE THREAD

**Issue by agdestine** [RoepStoep/lidraughts#9]
Hi to lidraughts team,

Is it possible to have the tournament description displayed somewhere on lidraughts app? If space is an issue, maybe instead of next to it on the FAQ button would be an option.

**Comment by RoepStoep** [comment]
Custom tournament descriptions are indeed currently not displayed in the app. I will include this in the next update for the app, and keep this issue updated. I don't think it will be a problem to display it on the top, above the tournament rankings.

**Comment by RoepStoep** [comment]
Tournament description is now displayed along with the streak/berserk settings: https://github.com/RoepStoep/lidrobile/commit/d2c5e6d83c747a308485c1e9f865bcf7e91e0e4e

The update will be submitted to the app/play stores tonight, so it should be available soon
